### ISSUE TITLE
play.py (23) - IndexError: list index out of range

### ISSUE THREAD

**Issue by fermanis** [aussieaddons/plugin.video.netball-live#332]
Unable to play any videos.

Log file here: https://paste.kodi.tv/kosetutaso

**Comment by glennguy** [comment]
@fermanis Thanks for the detailed log. Looks like all the catch up video menus are broken too. I'll try and get onto it today.
As for watching the live matches later today as I can't commit to definitely getting it fixed before then - try lowering the quality setting by one value and retrying, and again if it still fails. It looks like the amount of different streams/bitrates that are available has decreased so that's what I'll need to adjust.

**Comment by fermanis** [comment]
I'll try that, thanks

**Comment by fermanis** [comment]
update - I tried all the quality settings today, and still couldn't get it to work.

**Comment by glennguy** [comment]
@fermanis Just pushed an update (v1.2.0), it should be in the repo in now!

If you can't see the update:
(in estuary skin)
go to add-ons
click the open box icon at the top left
install from repository
right click/long press/ 'c' button on our repo and select 'Check For Updates'
should be there now.

Let me know how you go

Glenn

**Comment by fermanis** [comment]
Thanks, the current live game is working.
